baseurl: "https://shubhamoulkar.netlify.app/"
languageCode: "en-us"
title: "Shubham Oulkar"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Projects
      url: "projects/"
      weight: 3
    - name: blogs
      url: "post/"
      weight: 4

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Shubham Oulkar](https://github.com/ShubhamOulkar/website.git) 2021 | [Github](https://github.com/ShubhamOulkar) | [Twitter](https://twitter.com/shubhuoulkar) | [LinedIn](https://linkedin.com/in/shubham-oulkar-372797217)"

markup:
  goldmark:
    renderer:
      unsafe: true
